language: node_js
node_js:
- 4.3.1
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
  code_climate:
    repo_token: 9a0524d06a72b026a3d9b1ad9c889d3e11a69311be659448086a0327651439f2
deploy:
  provider: npm
  email: technique@yocto.re
  api_key:
    secure: HTDgqnxt9HR9bqSHcVSlM8glRYu9aWGw0LztsZsXUR5Qi8JbBCaWrPKgO9e2nVmLAO6AQoZmbU+K1GXPgkJuQP52fYEnfq6f6i2bdBK36Til9TDJmW/luK4cpZD2kIt4w0Vm8cS18RPwRMoiS/OQ8q8tpuGbeZEKmeVVNZLR0TUl0DAdMQqoV02mFPAE9nmlt4aFATYpoaInEhCQXzTCNB0wR7i5rCK/a3QMEoxe6weZmJaJ8SPR80B5jNjpeV6wvlEUTbB7sFK04JehecmTjoFfmJsdcCu2KGDbz4NyIRFqCshWD2mp9T5iMC/T4UKfpR4dEg7ClB81x1jArM9eG0Uk6iC6x9UOLmZ+UD2vyzFrr3sHgkx9L3LrDd2PjUAeLOdUoTv2oa1kQR6FB3ft/JgVgCrNYsxdFPU/dbHU2QE5EMKORFuMQ7n88blC1/ovFT1JfTkiP89whLdXvZBUu8Pc87SjJjrkegRTLN93wBeQyN3jtmaH8D/hE9+s/P+scGyJKCzWo5Sf9K4TV+Wa5qKLyPhQ1p086Xsm0jshDw6Gc9kUPIroK0epdealI+b3Sg4doKMIoEk7dkINB4aWSBdAAJDMB7qGEOdBHjToqaWjbti1pbFp528s6+2BVCBp5XmkgspKI1CbFE9kwgYxY+d4GUFZCsrsYkfVrWItd4I=
  on:
    tags: true
    repo: yoctore/yocto-orika
before_install: npm install -g grunt-cli
install: npm install
